describe("match.emaillogin", function()
	local t, is, emaillogin
	setup(function()
    t = require "t"
    is = t.is
    emaillogin = t.matchu.emaillogin
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(emaillogin))
  end)
  it("positive", function()
    assert.equal('x', emaillogin('x@site.com'))
    assert.equal('any', emaillogin('any@site.info'))
    assert.equal('any', emaillogin(' any@site.info'))
    assert.equal('any', emaillogin('^any@site.info'))
    assert.equal('1', emaillogin('1@site.COM'))
    assert.equal('me', emaillogin('me@сайт.рф'))
    assert.equal('a', emaillogin('a@xxx.сайт.рф'))
  end)
  it("negative", function()
    assert.is_nil(emaillogin('8.8.8.8'))
    assert.is_nil(emaillogin('com'))
    assert.is_nil(emaillogin('.com'))
    assert.is_nil(emaillogin('com.ru'))
    assert.is_nil(emaillogin('.com.ru'))
    assert.is_nil(emaillogin('.'))
    assert.is_nil(emaillogin('.local'))
    assert.is_nil(emaillogin('local'))
    assert.is_nil(emaillogin({}))
    assert.is_nil(emaillogin({'type'}))
    assert.is_nil(emaillogin(0))
    assert.is_nil(emaillogin(''))
    assert.is_nil(emaillogin(false))
    assert.is_nil(emaillogin(true))
    assert.is_nil(emaillogin('@'))
    assert.is_nil(emaillogin('@a'))
  end)
  it("nil", function()
    assert.is_nil(emaillogin(nil))
    assert.is_nil(emaillogin())
  end)
end)