describe("match.idn", function()
	local t, is, idn
	setup(function()
    t = require "t"
    is = t.is
    idn = is.idn
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(idn))
  end)
  it("positive", function()
    assert.is_true(idn('xn--wgv71a119e.jp'))
  end)
  it("negative", function()
    assert.is_nil(idn('8.8.8.8'))
    assert.is_nil(idn('com'))
    assert.is_nil(idn('.'))
    assert.is_nil(idn('.local'))
    assert.is_nil(idn('local'))
    assert.is_nil(idn({}))
    assert.is_nil(idn({'type'}))
    assert.is_nil(idn(0))
    assert.is_nil(idn(''))
    assert.is_nil(idn(false))
    assert.is_nil(idn(true))
    assert.is_nil(idn('xxx.site.info'))
  end)
  it("nil", function()
    assert.is_nil(idn(nil))
    assert.is_nil(idn())
  end)
end)