describe("is.ip", function()
	local t, is, ip, host
	setup(function()
    t = require "t"
    is = t.is
    ip = t.net.ip
    host = t.net.host
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(is.ip))
  end)
  it("positive", function()
    assert.is_true(is.ip('8.8.8.8'))
    assert.is_true(is.ip(ip('8.8.8.8')))
    assert.is_true(is.ip(host('8.8.8.8')))
  end)
  it("negative", function()
    assert.is_nil(is.ip('com'))
    assert.is_nil(is.ip('.com'))
    assert.is_nil(is.ip('com.ru'))
    assert.is_nil(is.ip('.com.ru'))
    assert.is_nil(is.ip('.'))
    assert.is_nil(is.ip('.local'))
    assert.is_nil(is.ip('local'))
    assert.is_nil(is.ip({}))
    assert.is_nil(is.ip({'type'}))
    assert.is_nil(is.ip(0))
    assert.is_nil(is.ip(''))
    assert.is_nil(is.ip(false))
    assert.is_nil(is.ip(true))
  end)
  it("nil", function()
    assert.is_nil(is.ip(nil))
    assert.is_nil(is.ip())
  end)
end)