describe("is.net.ip", function()
	local t, is, ip
	setup(function()
    t = require "t"
    is = t.is
    ip = t.net.ip
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(is.net.ip))
  end)
  it("positive", function()
    assert.is_true(is.net.ip('8.8.8.8'))
    assert.is_true(is.net.ip(ip('8.8.8.8')))
--    assert.is_true(is.net.ip(host('8.8.8.8')))
  end)
  it("negative", function()
    assert.is_nil(is.net.ip('com'))
    assert.is_nil(is.net.ip('.com'))
    assert.is_nil(is.net.ip('com.ru'))
    assert.is_nil(is.net.ip('.com.ru'))
    assert.is_nil(is.net.ip('.'))
    assert.is_nil(is.net.ip('.local'))
    assert.is_nil(is.net.ip('local'))
    assert.is_nil(is.net.ip({}))
    assert.is_nil(is.net.ip({'type'}))
--    assert.is_nil(is.net.ip(0))
    assert.is_nil(is.net.ip(''))
    assert.is_nil(is.net.ip(false))
    assert.is_nil(is.net.ip(true))
  end)
  it("nil", function()
    assert.is_nil(is.net.ip(nil))
    assert.is_nil(is.net.ip())
  end)
end)