describe("is.localdomain", function()
	local t, is, domain, host
	setup(function()
    t = require "t"
    is = t.is
    domain = t.net.domain
    host = t.net.host
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(domain))
    assert.truthy(is.callable(is.net.localdomain))
  end)
  it("positive", function()
    assert.is_true(is.net.localdomain('my.local'))
    assert.is_true(is.net.localdomain(domain('my.local')))
    assert.is_true(is.net.localdomain(host('my.local')))
  end)
  it("negative", function()
    assert.is_nil(is.net.localdomain('site.com'))
    assert.is_nil(is.net.localdomain(domain('site.com')))
    assert.is_nil(is.net.localdomain(host('site.com')))

    assert.is_nil(is.net.localdomain('8.8.8.8'))
    assert.is_nil(is.net.localdomain('com'))
    assert.is_nil(is.net.localdomain('.com'))
    assert.is_nil(is.net.localdomain('com.ru'))
    assert.is_nil(is.net.localdomain('.com.ru'))
    assert.is_nil(is.net.localdomain('.'))
    assert.is_nil(is.net.localdomain('.local'))
    assert.is_nil(is.net.localdomain('local'))
    assert.is_nil(is.net.localdomain({}))
    assert.is_nil(is.net.localdomain({'type'}))
    assert.is_nil(is.net.localdomain(0))
    assert.is_nil(is.net.localdomain(''))
    assert.is_nil(is.net.localdomain(false))
    assert.is_nil(is.net.localdomain(true))
  end)
  it("nil", function()
    assert.is_nil(is.net.localdomain(nil))
    assert.is_nil(is.net.localdomain())
  end)
end)