describe("is.tld", function()
	local t, is
	setup(function()
    t = require "t"
    is = t.is
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(is.tld))
  end)
  it("positive", function()
    assert.is_true(is.tld('COM'))
    assert.is_true(is.tld('CoM'))
    assert.is_true(is.tld('com'))
    assert.is_true(is.tld('.com'))
    assert.is_true(is.tld('.рф'))
    assert.is_true(is.tld('.info'))
    assert.is_true(is.tld('com.ru'))
    assert.is_true(is.tld('.com.ru'))
  end)
  it("negative", function()
    assert.is_nil(is.tld('8.8.8.8'))
    assert.is_nil(is.tld(''))
    assert.is_nil(is.tld('.'))
    assert.is_nil(is.tld('.local'))
    assert.is_nil(is.tld('local'))
    assert.is_nil(is.tld({}))
    assert.is_nil(is.tld({'type'}))
    assert.is_nil(is.tld(0))
    assert.is_nil(is.tld(''))
    assert.is_nil(is.tld(false))
    assert.is_nil(is.tld(true))
  end)
  it("nil", function()
    assert.is_nil(is.tld(nil))
    assert.is_nil(is.tld())
  end)
end)