describe("host", function()
	local t, is, host, tld, ip
	setup(function()
    t = require "t"
    is = t.is
    host = t.net.host
    tld = t.net.tld
    ip = t.net.ip
	end)
  it("meta", function()
    assert.truthy(is)
    assert.truthy(is.callable(host))

    assert.is_true(is.net.host(host('site.com.')))
    assert.is_table(host('site.com'))
    assert.is_table(getmetatable(host('site.com')))
  end)
  it("positive", function()
    assert.equal('site.com', tostring(host('site.com')))
    assert.equal('site.com', tostring(host('site.com.')))
    assert.equal('site.com', tostring(host('.site.com')))
    assert.equal('site.com', tostring(host('.site.com.')))
    assert.equal('site.com', tostring(host('site.com-')))
    assert.equal('site.com', tostring(host('site.COM')))
    assert.equal('site.com', tostring(host('site.CoM')))
    assert.equal('site.com', tostring(host('SITE.COM')))

--    assert.equal('сайт.рф', tostring(host('сайт.рф')))
--    assert.equal('сайт.рф', tostring(host('xxx.сайт.рф')))
--    assert.equal('сайт.рф', tostring(host('любой.сайт.рф')))

    assert.equal('xxx.site.info', tostring(host('xxx.site.info')))
    assert.equal('my.local', tostring(host('my.local')))
    assert.equal('xxx.my.local', tostring(host('xxx.my.local')))
    assert.equal('yyy.xxx.my.local', tostring(host('yyy.xxx.my.local')))

    assert.equal('com', tostring(host('com')))
    assert.equal('com', tostring(host('.com')))
    assert.equal('com.ru', tostring(host('com.ru')))
    assert.equal('com.ru', tostring(host('.com.ru')))

    assert.equal('local', tostring(host('.local')))
    assert.equal('local', tostring(host('local')))
    assert.equal('type', tostring(host({'type'})))

    assert.equal('8.8.8.8', tostring(host('8.8.8.8')))
  end)
  it("__eq", function()
    assert.equal(host('site.com'), host('site.com'))
    assert.equal(host('site.info'), host('site.info'))
  end)
  it("__concat", function()
    assert.equal(host('www.site.com'), host('site.com') .. 'www')
    assert.equal(host('www.site.com'), host('site.com') .. {'www'})
    assert.equal(host('1.1.1.1.in-addr.arpa'), host('in-addr.arpa') .. ip('1.1.1.1'))
    assert.is_nil(host('8.8.8.8') .. 'www')
    assert.is_nil(host(ip('8.8.8.8')) .. 'www')
  end)
  it(".tld", function()
    assert.equal(tld('com'), host('site.com').tld)
    assert.equal(tld('site.com'), host('site.com').tld)
    assert.equal(tld('xxx.site.info'), host('xxx.site.info').tld)
  end)
  it("ip", function()
    assert.equal(tld('com'), host('site.com').tld)
    assert.equal(tld('site.com'), host('site.com').tld)
    assert.equal(tld('xxx.site.info'), host('xxx.site.info').tld)
  end)
  it("negative", function()
    assert.is_nil(host('.'))
    assert.is_nil(host({}))
    assert.is_nil(host(0))
    assert.is_nil(host(''))
    assert.is_nil(host(false))
    assert.is_nil(host(true))

    assert.not_equal(host('site.com'), host('site.info'))
    assert.not_equal(host('xxx.site.com'), host('site.com'))
  end)
  it("nil", function()
    assert.is_nil(host(nil))
    assert.is_nil(host())
  end)
end)